---
title: "p8105_hw2_hy2669"
author: "Haoyang Yi"
date: "2020/9/27"
output: github_document
---
## Problem 1
```{r}
library(tidyverse)
library(readxl)
trashwheel=read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet='Mr. Trash Wheel',
                      range=cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls=round(sports_balls),
         sports_balls=as.integer(sports_balls)) # there are 14 observations
#read precipitation of 2017 and 2018 separately
precip_2018=read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet='2018 Precipitation',skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year=2018) %>%
  relocate(year)

precip_2017=read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet='2017 Precipitation',skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year=2017) %>%
  relocate(year)
# combine annual precipitation
month_df=tibble(month=1:12,
                month_name=month.name)
precip_df=bind_rows(precip_2018,precip_2017)
left_join(precip_df,month_df,by='month') 

sum(precip_df$total[precip_df$year==2018])
median(trashwheel$sports_balls[trashwheel$year==2017])
# # There are 4 observations in precipitation dataset for 2017 and 2018.There are 14 observations in Mr.Trash Wheel sheet dataset. The total precipitation in 2018 is 70.33. The median number of sports balls in a dumpster in 2017 is 8.
```

## Problem 2
```{r}
nyc_transit_df=read_csv('./data/problem2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv')  
  nyc_transit_df=janitor::clean_names(nyc_transit_df) %>% 
  select(line,station_name,station_latitude,station_longitude,route1:route11,entry,vending,entrance_type, ada) %>%
  mutate(entry=recode(entry,"YES"="TRUE","NO"="FALSE")) %>%
  mutate(entry=as.logical(entry)) 
  str(nyc_transit_df)
  # This dataset contains information of stations including names,locations,routes they serve,entrance type, ADA compliance,entry and vending status. Data cleaning steps: read the data-clean the name-select columns to retain-convert the entry variable from character to logical.The resulting dataset has 19 colums and 1868 rows.These data are not tidy since there are too many route columns, and route1:route7 are character variables while route8:route11 are numeric variables.
  
  nyc_station<-distinct(nyc_transit_df,station_name,line) 
  nrow(nyc_station)# there are 465 distinct stations.
  count(nyc_transit_df,ada) # 468 stations are ADA compliant.
  nyc=filter(nyc_transit_df,vending=='NO') # station without vending allow entrance (entry/exit) 
  nrow(nyc)/ nrow(nyc_transit_df) # the proportion = number of stations without vending allow entrance(entry/exit)/ total number of entrance/exit = 0.098
  nyc_tidy_df= nyc_transit_df %>%
  mutate_at(vars(route1:route11),as.character) %>%
  pivot_longer(route1:route11,names_to='route_name',names_prefix='route',
               values_to='route_number') %>%
  drop_na(route_number) %>%
  print() # Reformat the data so that the route number and route name are distinct variables
  a_df<-filter(nyc_tidy_df,route_number=='A')
  nrow(distinct(a_df,station_name,line)) # there are 60 distinct stations serve the A train
  ada_df=filter(a_df,ada=='TRUE')
  nrow(distinct(ada_df,station_name,line)) # Of the stations that serve the A train,17 are ADA compliant
```

## Problem 3
```{r}
plot(pressure)
```

