p8105\_hw2\_hy2669
================
Haoyang Yi
2020/9/27

``` r
library(tidyverse)
```

    ## -- Attaching packages -------------------------------------------------------------- tidyverse 1.3.0 --

    ## √ ggplot2 3.3.2     √ purrr   0.3.4
    ## √ tibble  3.0.3     √ dplyr   1.0.2
    ## √ tidyr   1.1.2     √ stringr 1.4.0
    ## √ readr   1.3.1     √ forcats 0.5.0

    ## -- Conflicts ----------------------------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

``` r
trashwheel = read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet = 'Mr. Trash Wheel',
                      range = cell_cols("A:N")) 
trashwheel = janitor::clean_names(trashwheel) %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = round(sports_balls)) %>%
  mutate(sports_balls = as.integer(sports_balls)) %>%
  print() # there are 14 observations
```

    ## Warning in FUN(X[[i]], ...): strings not representable in native encoding will
    ## be translated to UTF-8

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00C4>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00D6>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00E4>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00F6>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00DF>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00C6>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00E6>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00D8>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00F8>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00C5>' to native encoding

    ## Warning in FUN(X[[i]], ...): unable to translate '<U+00E5>' to native encoding

    ## # A tibble: 344 x 14
    ##    dumpster month  year date                weight_tons volume_cubic_ya~
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>            <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31               18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74               13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45               15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06               18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71               13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52               14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76               18
    ## # ... with 334 more rows, and 8 more variables: plastic_bottles <dbl>,
    ## #   polystyrene <dbl>, cigarette_butts <dbl>, glass_bottles <dbl>,
    ## #   grocery_bags <dbl>, chip_bags <dbl>, sports_balls <int>,
    ## #   homes_powered <dbl>

``` r
# read precipitation of 2017 and 2018 separately
precip_2018 = read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet = '2018 Precipitation',skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 = read_xlsx('./data/problem1/Trash-Wheel-Collection-Totals-8-6-19.xlsx',
                      sheet ='2017 Precipitation',skip = 1) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
# combine annual precipitation
month_df = tibble(month = 1:12,
                month_name = month.name)
precip_df = bind_rows(precip_2018,precip_2017)
left_join(precip_df,month_df,by ='month') 
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # ... with 14 more rows

``` r
sum(precip_df$total[precip_df$year == 2018])
```

    ## [1] 70.33

``` r
median(trashwheel$sports_balls[trashwheel$year == 2017])
```

    ## [1] 8

There are 4 observations in precipitation dataset for 2017 and
2018.There are 14 observations in Mr.Trash Wheel sheet dataset. The
total precipitation in 2018 is 70.33. The median number of sports balls
in a dumpster in 2017 is 8.

## Problem 2

``` r
nyc_transit_df = read_csv('./data/problem2/NYC_Transit_Subway_Entrance_And_Exit_Data.csv')  
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
  nyc_transit_df = janitor::clean_names(nyc_transit_df) %>% 
  select(line,station_name,station_latitude,station_longitude,
         route1:route11,entry,vending,entrance_type, ada) %>%
  mutate(entry = recode(entry,"YES"="TRUE","NO"="FALSE")) %>%
  mutate(entry = as.logical(entry)) 
  str(nyc_transit_df)
```

    ## tibble [1,868 x 19] (S3: tbl_df/tbl/data.frame)
    ##  $ line             : chr [1:1868] "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name     : chr [1:1868] "25th St" "25th St" "36th St" "36th St" ...
    ##  $ station_latitude : num [1:1868] 40.7 40.7 40.7 40.7 40.7 ...
    ##  $ station_longitude: num [1:1868] -74 -74 -74 -74 -74 ...
    ##  $ route1           : chr [1:1868] "R" "R" "N" "N" ...
    ##  $ route2           : chr [1:1868] NA NA "R" "R" ...
    ##  $ route3           : chr [1:1868] NA NA NA NA ...
    ##  $ route4           : chr [1:1868] NA NA NA NA ...
    ##  $ route5           : chr [1:1868] NA NA NA NA ...
    ##  $ route6           : chr [1:1868] NA NA NA NA ...
    ##  $ route7           : chr [1:1868] NA NA NA NA ...
    ##  $ route8           : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route9           : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route10          : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route11          : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ entry            : logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ vending          : chr [1:1868] "YES" "YES" "YES" "YES" ...
    ##  $ entrance_type    : chr [1:1868] "Stair" "Stair" "Stair" "Stair" ...
    ##  $ ada              : logi [1:1868] FALSE FALSE FALSE FALSE FALSE FALSE ...

This dataset contains information of stations including
names,locations,routes they serve,entrance type, ADA compliance,entry
and vending status. Data cleaning steps: read the data-clean the
name-select columns to retain-convert the entry variable from character
to logical.The resulting dataset has 19 columns and 1868 rows.These data
are not tidy since there are too many route columns, and route1:route7
are character variables while route8:route11 are numeric variables.

``` r
  nyc_station<-distinct(nyc_transit_df,station_name,line) # get distinct stations based on name and line.
  nrow(nyc_station)# there are 465 distinct stations.
```

    ## [1] 465

``` r
  count(nyc_transit_df,ada) # 468 stations are ADA compliant.
```

    ## # A tibble: 2 x 2
    ##   ada       n
    ##   <lgl> <int>
    ## 1 FALSE  1400
    ## 2 TRUE    468

``` r
  nyc = filter(nyc_transit_df,vending =='NO') # station without vending 
  nycentry = filter(nyc,entry == TRUE) # station without vending allow entrance
  nrow(nycentry)/nrow(nyc) # the proportion = number of stations without vending allow entrance/ total number of stations without vending = 0.377
```

    ## [1] 0.3770492

``` r
  nyc_tidy_df = nyc_transit_df %>%
  mutate_at(vars(route1:route11),as.character) %>%
  pivot_longer(route1:route11,names_to ='route_name',names_prefix ='route',
               values_to ='route_number') %>%
  drop_na(route_number) %>%
  print() # Reformat the data so that the route number and route name are distinct variables
```

    ## # A tibble: 4,270 x 10
    ##    line  station_name station_latitude station_longitu~ entry vending
    ##    <chr> <chr>                   <dbl>            <dbl> <lgl> <chr>  
    ##  1 4 Av~ 25th St                  40.7            -74.0 TRUE  YES    
    ##  2 4 Av~ 25th St                  40.7            -74.0 TRUE  YES    
    ##  3 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  4 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  5 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  6 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  7 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  8 4 Av~ 36th St                  40.7            -74.0 TRUE  YES    
    ##  9 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ## 10 4 Av~ 45th St                  40.6            -74.0 TRUE  YES    
    ## # ... with 4,260 more rows, and 4 more variables: entrance_type <chr>,
    ## #   ada <lgl>, route_name <chr>, route_number <chr>

``` r
  a_df<-filter(nyc_tidy_df,route_number =='A')
  nrow(distinct(a_df,station_name,line)) # there are 60 distinct stations serve the A train
```

    ## [1] 60

``` r
  ada_df = filter(a_df,ada =='TRUE')
  nrow(distinct(ada_df,station_name,line)) # Of the stations that serve the A train,17 are ADA compliant
```

    ## [1] 17

## Problem 3

``` r
pols_month_df = read_csv('./data/problem3/pols-month.csv') 
```

    ## Parsed with column specification:
    ## cols(
    ##   mon = col_date(format = ""),
    ##   prez_gop = col_double(),
    ##   gov_gop = col_double(),
    ##   sen_gop = col_double(),
    ##   rep_gop = col_double(),
    ##   prez_dem = col_double(),
    ##   gov_dem = col_double(),
    ##   sen_dem = col_double(),
    ##   rep_dem = col_double()
    ## )

``` r
snp_df = read_csv('./data/problem3/snp.csv')
```

    ## Parsed with column specification:
    ## cols(
    ##   date = col_character(),
    ##   close = col_double()
    ## )

``` r
unemployment_df = read_csv('./data/problem3/unemployment.csv')
```

    ## Parsed with column specification:
    ## cols(
    ##   Year = col_double(),
    ##   Jan = col_double(),
    ##   Feb = col_double(),
    ##   Mar = col_double(),
    ##   Apr = col_double(),
    ##   May = col_double(),
    ##   Jun = col_double(),
    ##   Jul = col_double(),
    ##   Aug = col_double(),
    ##   Sep = col_double(),
    ##   Oct = col_double(),
    ##   Nov = col_double(),
    ##   Dec = col_double()
    ## )

``` r
  pols_month_df = separate(pols_month_df,mon,into = c('year','month','day')) %>%
  mutate(month = month.abb[as.factor(month)]) %>% # replace month number with month name
  mutate(president = recode(prez_gop,'0'='dem','1'='gop','2'='abnormal')) %>% 
  mutate(year = as.integer(year)) %>%  # convert year variable to integer 
  select(-prez_dem,-prez_gop,-day) # separate mon into year month and day. 
# Create president variable to show the party that the president belongs. remove prez_dem, prez_gop and day variables
  snp_df = separate(snp_df,date,into=c('month','day','year')) %>%
  arrange(year,month) %>% # arrange according to year and month
  mutate(month = month.abb[as.factor(month)]) %>% 
  mutate(year = as.integer(year)) %>% 
  select(year,month,close)  # clean and tidy the data in snp.csv,organize columns.
  unemployment_df = pivot_longer(unemployment_df,Jan:Dec,names_to = 'month',
                                 values_to = 'rate of unemployment') %>%
  rename(year = Year) # switch the unemployment dataset to 'long'
  # rename the Year variable to year according to name of variable in pols_month and snp datasets.
two_df = left_join(pols_month_df,snp_df) 
```

    ## Joining, by = c("year", "month")

``` r
final_df = left_join(two_df,unemployment_df) # first, merge snp into pols, then merge unemployment in to the previous result.
```

    ## Joining, by = c("year", "month")

The pols dataset contains numbers of republican and democratic national
politicians on associated date.The snp dataset contains closing values
fo S\&P stock index on the associated date. The unemployment dataset
contains percentage of unemployment in each month of the associated
year.

|                                                  |           |
| :----------------------------------------------- | :-------- |
| Name                                             | final\_df |
| Number of rows                                   | 822       |
| Number of columns                                | 11        |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_   |           |
| Column type frequency:                           |           |
| character                                        | 2         |
| numeric                                          | 9         |
| \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ |           |
| Group variables                                  | None      |

Data summary

**Variable type: character**

| skim\_variable | n\_missing | complete\_rate | min | max | empty | n\_unique | whitespace |
| :------------- | ---------: | -------------: | --: | --: | ----: | --------: | ---------: |
| month          |          0 |              1 |   3 |   3 |     0 |        12 |          0 |
| president      |          0 |              1 |   3 |   8 |     0 |         3 |          0 |

**Variable type: numeric**

| skim\_variable       | n\_missing | complete\_rate |    mean |     sd |      p0 |     p25 |     p50 |     p75 |   p100 | hist  |
| :------------------- | ---------: | -------------: | ------: | -----: | ------: | ------: | ------: | ------: | -----: | :---- |
| year                 |          0 |           1.00 | 1980.75 |  19.79 | 1947.00 | 1964.00 | 1981.00 | 1998.00 | 2015.0 | ▇▇▇▇▇ |
| gov\_gop             |          0 |           1.00 |   22.48 |   5.68 |   12.00 |   18.00 |   22.00 |   28.00 |   34.0 | ▆▆▇▅▅ |
| sen\_gop             |          0 |           1.00 |   46.10 |   6.38 |   32.00 |   42.00 |   46.00 |   51.00 |   56.0 | ▃▃▇▇▇ |
| rep\_gop             |          0 |           1.00 |  194.92 |  29.24 |  141.00 |  176.00 |  195.00 |  222.00 |  253.0 | ▃▇▆▃▅ |
| gov\_dem             |          0 |           1.00 |   27.20 |   5.94 |   17.00 |   22.00 |   28.00 |   32.00 |   41.0 | ▆▅▇▆▂ |
| sen\_dem             |          0 |           1.00 |   54.41 |   7.37 |   44.00 |   48.00 |   53.00 |   58.00 |   71.0 | ▇▆▇▃▂ |
| rep\_dem             |          0 |           1.00 |  244.97 |  31.37 |  188.00 |  211.00 |  250.00 |  268.00 |  301.0 | ▇▂▇▇▅ |
| close                |         39 |           0.95 |  466.67 | 535.05 |   17.05 |   83.48 |  135.76 |  918.03 | 2104.5 | ▇▁▂▁▁ |
| rate of unemployment |         12 |           0.99 |    5.83 |   1.65 |    2.50 |    4.70 |    5.60 |    6.90 |   10.8 | ▃▇▅▂▁ |

The dimension of the resulting dataset is 822 rows and 11 columns. The
range of years is 1947-2015. Key variables are president(republican or
democratic), numbers of republican and democratic governors,senators and
representatives, closing values of S\&P stock index, precentage of
unemployment.
